Portal-only mode
Scrivito/scrivito-portal-app pull request #240
Opened 2024-01-15 11:35 UTC by apepper

2024-01-15 14:07 UTC, dcsaszar requested changes
See comments.

* [ ] FYI I find the concept of a site property to make existing content inaccessible confusing. 

My naive expectation for a pure portal would be a site where "My Tynacoon" is the root.
By turning parts of the content effectively into redirects we create a situation where future development has to keep this aspect in mind, e.g., prerendering a sitemap would have to take the `sitePortalOnlyMode` setting into account.

2024-01-16 09:53 UTC, apepper commented on src/Objs/Homepage/HomepageLayoutComponent.tsx
> +        if (isInPlaceEditingActive()) return
It was actually my plan to have the "preview mode" work as the actual site would. Otherwise I would have to show the notice also in preview mode.

2024-01-16 09:59 UTC, apepper commented on src/Objs/Homepage/HomepageLayoutComponent.tsx
> +      currentPageObjPath, // added, so that useEffect is triggered when currentPageObjPath changes
Nice find!

2024-01-16 10:06 UTC, apepper commented on src/Objs/Homepage/HomepageLayoutComponent.tsx
> +        window.location.replace(url)
The difference is the browser back button: With `Scrivito.navigateTo(portalOverviewPage)` the non-portal page may show up in the back button list and will also be retried, if once clicked "back". With `window.location.replace(url)` the browser will remember, that the non-portal page "is" actually the portal overview page.

2024-01-16 10:24 UTC, apepper commented
REVIEW ([d321f3d](https://github.com/Scrivito/scrivito-portal-app/pull/240/commits/d321f3d0e968c80abb8e39d95c10ad9bb2a33dd9))

I'm happy to discuss the design decisions in a voice call.

2024-01-16 11:25 UTC, dcsaszar commented on src/Objs/Homepage/HomepageLayoutComponent.tsx
> +        if (isInPlaceEditingActive()) return
This breaks the UI for editors:
* When I set portal mode to "yes" the UI showed completely different properties and I had no way of undoing the change.
* I was unable to navigate back to the homepage in the hierarchy.
* I was unable to click most of the pages in the hierarchy.

2024-01-16 11:26 UTC, dcsaszar commented on src/Objs/Homepage/HomepageLayoutComponent.tsx
> +        if (isInPlaceEditingActive()) return
> I would have to show the notice also in preview mode.

Yes, that's the only way to keep the UI functioning for editors.

2024-01-16 11:28 UTC, dcsaszar requested changes
See https://github.com/Scrivito/scrivito-portal-app/pull/240#discussion_r1452398756

We should make sure to keep that UX basics intact. Otherwise editors will be confused.

2024-01-16 12:08 UTC, apepper commented
REVIEW ([06feae6](https://github.com/Scrivito/scrivito-portal-app/pull/240/commits/06feae6b2c25818c687998b08d13bd5c449b2307))

2024-01-16 12:19 UTC, merged