uglify css for high contrast mode
Scrivito/scrivito-portal-app pull request #318
Opened 2024-02-29 12:39 UTC by agessler

Fix for https://trello.com/c/n5l4xLwL/93-high-contrast-mode

2024-02-29 13:09 UTC, apepper commented
To see this in action one can select "Increase contrast" in the Mac OS settings:

<img width="827" alt="high contrast mode" src="https://github.com/Scrivito/scrivito-portal-app/assets/86275/d6ead500-f2a8-4d9b-a2c9-b9a3e2747c5b">

2024-03-01 11:19 UTC, apepper requested changes
FEEDBACK ([a164ded](https://github.com/Scrivito/scrivito-portal-app/pull/318/commits/a164ded687330287571b870df9396c221cd3afe8))

Very nice 🚀!

I only found one smaller issue (see comments). I also did not yet was able to try it out with the real beamer in question.

2024-03-01 11:19 UTC, apepper commented on src/assets/stylesheets/index.scss
> +    border: 1px solid #777;
I found one place, where the border is not (yet) working nicely: In the `DataMessageWidget` - the arrow to the avatar should also have a border:

<img width="1103" alt="Screenshot 2024-03-01 at 12 12 08" src="https://github.com/Scrivito/scrivito-portal-app/assets/86275/883d2122-a3a9-4d63-8d41-cefa726a35eb">

2024-03-01 13:52 UTC, agessler commented
@apepper Fixed.. I saw this issue.. I was lazy yesterday.

2024-03-01 15:05 UTC, apepper approved these changes
LGTM ([990ba8a](https://github.com/Scrivito/scrivito-portal-app/pull/318/commits/990ba8a971e1f1ac2e5b16aa95af4dade999f1ba))

Nice 🚀!

2024-03-01 15:05 UTC, merged