Use "currentLanguage" instead of individual "addressFormat"
Scrivito/scrivito-portal-app pull request #454
Opened 2024-06-14 09:49 UTC by apepper

2024-06-14 10:25 UTC, dcsaszar requested changes
Technically this is OK. But content-wise it's questionable.
Currently we have a German address in both the EN and DE site.
A German address should be written [in German order](https://howtogermany.com/household/utilities/mailing-a-letter-to-germany/#:~:text=German%20addresses%20differ%20from%20those,in%20Germany%20are%20five%20digits.) regardless of the sender.

Options:
* Put a US address in the EN page (adjust the content to the logic)
* Always use German format (simplify the code)

2024-06-17 12:35 UTC, apepper commented
REVIEW ([a29556a](https://github.com/Scrivito/scrivito-portal-app/pull/454/commits/a29556a71b9ee7a9d6d73ba62297d7aff04fe8ad))

2024-06-17 13:11 UTC, dcsaszar approved these changes
Nice.

2024-06-17 13:11 UTC, dcsaszar commented on src/Widgets/AddressWidget/AddressWidgetComponent.tsx
> +    ]
* [ ] FYI the variable name is now out of order (component-wise)
* [ ] FYI now we only have one address line we could think about turning this into a single string attribute with any space-separated content. Not sure how much we/editors gain from making this structured.

2024-06-19 08:32 UTC, merged