Data search
Scrivito/scrivito-portal-app pull request #458
Opened 2024-06-17 14:39 UTC by dcsaszar

Content: https://edit-beta.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://dave-data-search.scrivito-portal-app.pages.dev/en/equipment?_scrivito_workspace_id=s33bdf5568004455&_scrivito_display_mode=diff

Heads up: The Pisa backend currently fails with a `400 Bad Request` b/c of the combination of `isCustomer` and fulltext `_search`. Ronald will look into it.

2024-06-18 11:57 UTC, apepper requested changes
FEEDBACK ([f15d02b](https://github.com/Scrivito/scrivito-portal-app/pull/458/commits/f15d02b02d7d3c209514602cf8efd2cfbb792630))

Nice start 🚀!

Content wise: Could you add search in more places? Gutfeeling: in tickets, quotes, orders and documents.

2024-06-18 11:57 UTC, apepper commented on src/Components/DataBatchContext.tsx
> +    const [search, setSearch] = useState<string | undefined>()
It looks like, that the `search` value sometimes is reused after navigating away from a page.

How to reproduce:
* Visit https://edit-beta.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://dave-data-search.scrivito-portal-app.pages.dev/en/equipment?_scrivito_workspace_id=s33bdf5568004455&_scrivito_display_mode=view
* Search for "clean"
* => only "Air cleaner" is shown
* Click on Orders

Expected: Open orders are visible.

Actual: No orders found.

2024-06-18 11:57 UTC, apepper commented on src/Widgets/DataSearchWidget/DataSearchWidgetEditingConfig.ts
> +    buttonSize: 'medium',
There is no `buttonSize` attribute for `DataSearchWidget`.

2024-06-19 15:18 UTC, dcsaszar commented
REVIEW

> in tickets, quotes, orders and documents

All done but documents. When I tried to search I never got a result.

2024-06-20 13:34 UTC, apepper requested changes
FEEDBACK ([60dad5f](https://github.com/Scrivito/scrivito-portal-app/pull/458/commits/60dad5f8bf6c5f6b118f0f9c3a2dedef6539972e))

Nice 🚀!

There are still some details left. I also added search to documents and reported the 500 error to Ronald.

2024-06-21 11:48 UTC, apepper reviewed
FEEDBACK ([bfa07e2](https://github.com/Scrivito/scrivito-portal-app/pull/458/commits/bfa07e231d79b9401e45ed4fa8a3ac4c325dfd2e))

Code-wise really nice. I still need to clarify if Pisa-Sales supports all search cases.

2024-07-11 12:33 UTC, merged