Add social cards editing
Scrivito/scrivito-portal-app pull request #461
Opened 2024-06-19 17:56 UTC by dcsaszar

Converted and simplified from Scrivito Example App.

I tried to stick with the original as closely as possible.
The styles look slightly different and may need some adjustments or rework.

2024-06-20 08:33 UTC, apepper requested changes
FEEDBACK ([8286dd2](https://github.com/Scrivito/scrivito-portal-app/pull/461/commits/8286dd266c1ec48bd2aac1319b81d6f3ef1ec1e5))

Nice start 🚀!

2024-06-20 08:33 UTC, apepper commented on src/utils/getMetadata.ts
> +}
FYI: For the `obj instanceof Obj && obj.objClass() === 'Image'` part I would prefer to introduce a `isImage` function similar to:

https://github.com/Scrivito/scrivito-portal-app/blob/2fb056eb94a9a3b07f9b4b0971283adcf2762b25/src/Objs/Homepage/HomepageObjClass.ts#L29-L33

2024-06-20 08:33 UTC, apepper commented on src/utils/getMetadata.ts
> +    }
`facebookAppId` is not defined on "Homepage". Please add it.

2024-06-20 08:33 UTC, apepper commented on src/utils/getMetadata.ts
> +  }
Same with `twitterSite`.

2024-06-20 08:33 UTC, apepper commented on src/Objs/defaultPageEditingConfig.ts
> +  ],
This validation is too restrictive. Please remove it.

2024-06-20 08:33 UTC, apepper commented on src/Objs/defaultPageEditingConfig.ts
> +    properties: ['tcCreator', 'tcDescription', 'ogDescription'],
If I'm not mistaken, this list is not complete. E.g. `tcImage` is missing.

2024-06-20 08:33 UTC, apepper commented on src/Objs/defaultPageAttributes.ts
> +export const defaultPageAttributes = {
Currently this is only used on `Homepage` and `Page`.

I think the following Obj types would also benefit from this:
* `SubnavigationOverview`
* `ProductOverview`, `ProductCategory` and `Product`

2024-06-24 10:13 UTC, apepper reviewed
FEEDBACK ([71326f7](https://github.com/Scrivito/scrivito-portal-app/pull/461/commits/71326f76a3dca94a69dfcbcd80707639c9ece31a))

Nice 🚀! Getting closer.

Please see my comment and also provide a working copy, where `robotsIndex` is set by most (or all?) pages.

2024-06-24 10:13 UTC, apepper commented on src/Objs/Homepage/HomepageObjClass.ts
> +    twitterSite: 'string',
Please prefix both attributes with `site`, e.g. `siteFacebookAppId` and `siteTwitterSite`.

2024-06-24 14:24 UTC, dcsaszar commented
> provide a working copy, where `robotsIndex` is set by most (or all?) pages.

All:
https://edit-beta.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://dave-social-cards.scrivito-portal-app.pages.dev/en?_scrivito_workspace_id=p902f870e3545df7&_scrivito_display_mode=view

* [ ] FYI there are now also five pages with a description > 175. I can fix this as soon as I can create more working copies. 😉

2024-06-25 06:54 UTC, apepper approved these changes
LGTM ([c14b5c4](https://github.com/Scrivito/scrivito-portal-app/pull/461/commits/c14b5c41e4e0f806ded6eb704ef58449c81c02fa))

Nice 🚀! Code-wise all good. I'll write separately about the needed code-changes.

2024-06-25 06:54 UTC, merged