ModalSpinner: better style
Scrivito/scrivito-portal-app pull request #510
Opened 2024-07-15 09:18 UTC by apepper

Motivation: Less js payload due to no modal from react-boostrap.

2024-07-15 14:26 UTC, dcsaszar requested changes
Nice. See comments for some small todos.

2024-07-15 14:26 UTC, dcsaszar commented on src/Components/ModalSpinner.tsx
> +    <dialog className="loader-dailog" ref={dialogRef}>
* [ ] Now that `Modal` no longer handles the keyboard input, we must prevent closing the dialog with Escape.

2024-07-16 11:47 UTC, agessler commented on src/assets/stylesheets/theme/loader.scss
> +.modal-backdrop {
Yes..
First... it didn't work in test. 
Second... I used just the bootstrap markup/style here. So nobody will be confused.

2024-07-16 12:07 UTC, dcsaszar commented on src/assets/stylesheets/theme/loader.scss
> +.modal-backdrop {
It looks like this in Chrome:
<img width="874" alt="image" src="https://github.com/user-attachments/assets/e911ff5d-5c0c-46c9-b0ee-05aaf4a60e77">

2024-07-16 12:21 UTC, agessler commented on src/assets/stylesheets/theme/loader.scss
> +.modal-backdrop {
Done now... :backdrop is not in editor visible like.. :after or :before.

2024-07-16 12:32 UTC, apepper commented
[ac9e284](https://github.com/Scrivito/scrivito-portal-app/pull/510/commits/ac9e2845107ad3b6407eb9549c48b6c632300ca1)

Fixed Safari as well.

2024-07-16 13:19 UTC, apepper commented
REVIEW ([848d8c5](https://github.com/Scrivito/scrivito-portal-app/pull/510/commits/848d8c5de7383c7d99ea6f9f4900dd7323e61ce5))

2024-07-16 14:08 UTC, dcsaszar approved these changes

2024-07-16 14:08 UTC, merged