Rip toClientParams
Scrivito/scrivito-portal-app pull request #555
Opened 2024-08-05 15:43 UTC by apepper

Moved the "convert blob to upload binary" logic from the `connection` to `DataFormContainerWidget`.

With this it is now possible to remove `toClientParams` and `convertBlobAttributes`. Only `blobToBinary` remains.

2024-08-05 16:35 UTC, dcsaszar requested changes
Nice. One comment.

2024-08-05 16:35 UTC, dcsaszar commented on src/Widgets/DataFormContainerWidget/DataFormContainerWidgetComponent.tsx
> +      : blobToBinaryPromises[0]!
* [ ] The old code did a `length === 1` check to allow for the bang cast. The `files` can be zero-length (https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/files#javascript). We could do `: blobToBinaryPromises[0] || null`.

2024-08-06 06:55 UTC, apepper commented
REVIEW ([a6b3d2c](https://github.com/Scrivito/scrivito-portal-app/pull/555/commits/a6b3d2c507fa9023ab7a8d7d359cf80edc536821))

2024-08-06 08:13 UTC, dcsaszar approved these changes

2024-08-06 08:13 UTC, merged