bg-transparent works in cards + color fixes
Scrivito/scrivito-portal-app pull request #641
Opened 2024-10-02 11:58 UTC by agessler

Fixes Issue
https://infopark.slack.com/archives/C050WJC9YU8/p1727089632703809

See in WC "🌈all the colors!1!🌈"

2024-10-02 14:45 UTC, dcsaszar requested changes
* [ ] `dark-grey` is missing from your test content but has issues
* [ ] `middle-grey` has issues inside `light-grey`, `middle-grey`, `dark-grey`

<img width="1055" alt="image" src="https://github.com/user-attachments/assets/95f632e9-6fdb-4af6-98fb-1fdeab651bb5">

2024-10-21 08:14 UTC, dcsaszar commented
@agessler

* [ ] FYI Please also check out the new Tick list widget icon colors. They may need the same or similar adjustments.

2024-10-21 12:08 UTC, agessler commented
@dcsaszar with latest commits all should work

2024-10-21 12:36 UTC, dcsaszar commented on src/assets/stylesheets/index.scss
> +.bagde.bg-middle-grey {
* [ ] Weird typo. Is this unused? FYI I also see two `.jr-list-bagde` selectors in the existing CSS.

2024-10-21 12:45 UTC, dcsaszar reviewed
Looks good so far.
See comment for a potential typo.
Also I added icon list widgets to the test working copy.
* [ ] Icon list colors often don't match a single icon color for some reason.

2024-10-21 15:02 UTC, dcsaszar requested changes
Icon lists look consistent now.
* [ ] But I see one more issue with white/light/grey boxes in dark boxes.

<img width="787" alt="image" src="https://github.com/user-attachments/assets/58f0c97a-8b1d-4b92-bc9b-587c86f7957e">


How about this (goes without `important`):

```scss
.card {
  &.bg-primary,
  &.bg-secondary,
  &.bg-dark-grey,
  &.bg-success,
  &.bg-info,
  &.bg-danger {
    .bi {
      color: #fff;
    }
  }

  &.bg-white,
  &.bg-middle-grey,
  &.bg-light-grey {
    .bi {
      color: var(--bs-primary);
    }
  }

  &.bg-transparent {
    box-shadow: none;
    color: inherit;
  }
}
```

2024-10-22 08:55 UTC, dcsaszar approved these changes

2024-10-22 08:55 UTC, merged